config/routes.rb
Envelope::Application.routes.draw do
  
  root 'homepage#index'
  
  get 'about',   to: 'homepage#about', as: :about
  get 'privacy', to: 'homepage#privacy', as: :privacy
  get 'errors', to: 'homepage#error'
  get 'errors/:status', to: 'homepage#error'
  get 'tour/:page', to: 'homepage#tour', as: :tour
  get 'tour', to: 'homepage#tour'
  
  get 'help',    to: 'support_requests#new', as: :help
  post 'help',   to: 'support_requests#create', as: :support_request_create
  
  get  'my_events', to: 'events#index', as: :my_events
  get 'my_events/:short_name', to: 'events#show', as: :main_event
  put  'my_events/:short_name', to: 'events#update'
  patch  'my_events/:short_name', to: 'events#update'
  
  delete 'events/:id', to: 'events#destroy', as: :events_destroy
  
  get 'my_events/:short_name/guests', to: 'guests#index', as: :guests_show
  post 'my_events/:short_name/parties', to: 'parties#create', as: :party_create
  post 'my_events/:short_name/guests', to: 'parties#create', as: :guests_create
  get 'my_events/:short_name/messages', to: 'messages#index', as: :messages_show
  
  get 'my_events/:short_name/guests/new', to: 'parties#new_guest', as: :guest_new
  get 'my_events/:short_name/parties/new', to: 'parties#new', as: :party_new
  get 'my_events/:short_name/parties/:id/edit', to: 'parties#edit', as: :party_edit
  put  'my_events/:short_name/parties/:id', to: 'parties#update'
  patch  'my_events/:short_name/parties/:id', to: 'parties#update', as: :party_patch

  resources :replies, only: [:create]

  devise_for :admins, path: '', path_names: {
    sign_in:  'login',
    sign_out: 'logout',
    sign_up:  'register', as: :new_user_registration
  }
  
  get ':event', to: 'reply_sets#hello', as: :site
  post ':event/attendance', to: 'reply_sets#new'
  post ':event/confirmation', to: 'reply_sets#create'
  post ':event/messages',   to: 'messages#create', as: :message_create
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  before_filter :authenticate_admin!, only: [:index]
  before_action :set_event, only: [:index]
  layout 'dashboard', only: [:index]
  
  def index
    
  end
  
  def create
    @message = UnexpectedGuestMessage.new(message_params)
    if @message.save
      render action: 'thanks', status: :created
    else
      render action: 'new'
    end
  end
  
  private
  
  def message_params
    params.require(:unexpected_guest_message)
      .permit(
        :main_event_id,
        :body,
        :first_name,
        :last_name)
  end
  
  def set_event
    @event = MainEvent.find_by_short_name params.require :short_name
  end
  
end

app/views/messages/index.html.haml
%main
  .page.messages
    %ul.messages
      - @event.unexpected_guest_messages.each do |message|
        %li.message
          %h3= message.full_name
          %p.body= message.body

app/views/messages/new.html.haml
.page.message_new
  = form_for @message, url: message_create_path do |message_form|

    = message_form.hidden_field :main_event_id, value: @message.main_event_id
    = message_form.hidden_field :first_name, value: @message.first_name
    = message_form.hidden_field :last_name, value: @message.last_name

    .field
      - greeting = t('hi_guest', name: @message.first_name)
      = message_form.label :body, t('hello_please_leave_a_message', greeting: greeting)
      = message_form.text_area :body, id: 'body'
    .field
      = message_form.submit t('send')

app/views/messages/thanks.html.haml
.page.message_thanks

  %p= t :thank_you_for_the_message