config/routes.rb
Envelope::Application.routes.draw do
  
  root 'homepage#index'
  
  get 'about',   to: 'homepage#about', as: :about
  get 'privacy', to: 'homepage#privacy', as: :privacy
  get 'errors', to: 'homepage#error'
  get 'errors/:status', to: 'homepage#error'
  get 'tour/:page', to: 'homepage#tour', as: :tour
  get 'tour', to: 'homepage#tour'
  
  get 'help',    to: 'support_requests#new', as: :help
  post 'help',   to: 'support_requests#create', as: :support_request_create
  
  get  'my_events', to: 'events#index', as: :my_events
  get 'my_events/:short_name', to: 'events#show', as: :main_event
  put  'my_events/:short_name', to: 'events#update'
  patch  'my_events/:short_name', to: 'events#update'
  
  delete 'events/:id', to: 'events#destroy', as: :events_destroy
  
  get 'my_events/:short_name/guests', to: 'guests#index', as: :guests_show
  post 'my_events/:short_name/parties', to: 'parties#create', as: :party_create
  post 'my_events/:short_name/guests', to: 'parties#create', as: :guests_create
  get 'my_events/:short_name/messages', to: 'messages#index', as: :messages_show
  
  get 'my_events/:short_name/guests/new', to: 'parties#new_guest', as: :guest_new
  get 'my_events/:short_name/parties/new', to: 'parties#new', as: :party_new
  get 'my_events/:short_name/parties/:id/edit', to: 'parties#edit', as: :party_edit
  put  'my_events/:short_name/parties/:id', to: 'parties#update'
  patch  'my_events/:short_name/parties/:id', to: 'parties#update', as: :party_patch

  resources :replies, only: [:create]

  devise_for :admins, path: '', path_names: {
    sign_in:  'login',
    sign_out: 'logout',
    sign_up:  'register', as: :new_user_registration
  }
  
  get ':event', to: 'reply_sets#hello', as: :site
  post ':event/attendance', to: 'reply_sets#new'
  post ':event/confirmation', to: 'reply_sets#create'
  post ':event/messages',   to: 'messages#create', as: :message_create
  
end

app/models/guest.rb
require 'invitation'
require 'reply'

class Guest < ActiveRecord::Base

  validates_presence_of :first_name,
    message: :first_or_last_name_required,
    unless: [
      :last_name?,
      :unknown_name?
    ]
  
  belongs_to :party
  has_one :main_event, through: :party
  has_many :invitations
  has_many :replies
  
  attr_accessor :has_focus
  
  after_create :create_party
  
  def self.find_by_name(name)
    query = <<-SQL
      first_name || \' \' || last_name = (?) OR
      first_name = (?) OR
      last_name = (?)
    SQL
    search = self.where(query, name, name, name)
    return search.first
  end
  
  def mononymous?
    return false if unknown_name
    last = first_name.blank? and !last_name.blank?
    first = last_name.blank? and !first_name.blank?
    first || last
  end
  
  def familiar_name
    if unknown_name
      Reply.where(guest: self).map(&:unknown_name).compact.last
    else
      first_name || last_name
    end
  end
  
  def unknown_and_blank_name
    unknown_name and first_name.blank? and last_name.blank?
  end
  
  def full_name
    if unknown_name
      return Reply.where(guest: self).map(&:unknown_name).compact.last
    end
    names = [first_name, last_name].compact
    if names.any? then names.join ' ' end
  end
  
  def party_members
    party.guests.reject { |g| g == self }
  end
  
  def invite_to(*events)
    events.each do |event|
      Invitation.where(guest: self, event: event).first_or_create
    end
  end
  
  def invited_to?(event)
    one = Invitation.where(guest: self, event: event).any?
    two = self.party.main_event == event
    one || two
  end
  
  def reply_to(event, status)  
    reply = Reply.create(guest: self, event: event, status: status)
  end
  
  def replied_to?(event)  
    Reply.where(guest: self, event: event).any?
  end
  
  def events_invited
    main = self.party.main_event
    unless main.companion_events.any?
      return [main]
    end
    ces = main.companion_events.select do |event|
      self.invited_to?(event)
    end
    [main].concat ces
  end
  
  def events_attending
    events = self.events_invited
    events.select do |event|
      reply = Reply.where(guest: self, event: event).last(1)
      reply[0] && reply[0].status == true
    end
  end
  
  def events_not_attending
    events = self.events_invited
    events.select do |event|
      reply = Reply.where(guest: self, event: event).last(1)
      reply[0] && reply[0].status == false
    end
  end
  
  def status_for(event)
    
    last_reply = Reply.where(event: event, guest: self).last
    confirmed = last_reply ? (last_reply.status == true) : nil
    declined = last_reply ? (last_reply.status == false) : nil
    invited = self.invited_to?(event)
    
    if confirmed
      return :confirmed
    elsif declined
      return :declined
    elsif invited
      return :invited
    else
      return :not_invited
    end
  end
  
  def focus
    self.has_focus = true
  end
  
  def unfocus
    self.has_focus = false
  end
  
  def <=>(other)
    self.has_focus ? 0 : 1
  end
  
  private
  
  def create_party
    unless self.party
      self.party = Party.create!
      self.save!
    end
  end
  
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  
  before_filter :authenticate_admin!
  
  before_action :set_event, only: [:index]
  
  layout 'dashboard'
  
  # No apparent way to add new child records in a form.
  # Initializing 'a big number', and displaying as needed.
  MAX_GUESTS_IN_PARTY = 10
  
  def index
  end

  private
  
  def set_event
    @event = current_admin.main_events.find_by_short_name(params[:short_name])
  end

end

app/views/guests/index.haml
%main
  .page.guests
    .actions
      = link_to guest_new_path(@event), {class: 'btn'} do
        = t(:add_guest)
      = link_to party_new_path(@event), {class: 'btn'} do
        = t(:add_party)
    - if @event.parties.empty?
      %p=t :no_guests_yet
    - else
      %table
        %thead
          - column_count = (@event.companion_events.count + 2)
          - column_class = "with_"+([column_count, 4].min).to_s+"_columns"
          %tr{class: column_class}
            %th.name= t :name
            %th.event
              = t(:status, kind: @event.kind)
            -@event.companion_events.each do |event|
              %th.event
                = t(:status, kind: event.kind)
        - @event.parties.each do |party|
          %tbody.party{id: party.id }
            %tr.party{class: column_class}
              - count = @event.companion_events.count + 1
              %td{ colspan: count+1 }
                = party.name
                %span.edit
                  = link_to t(:edit_this_party), party_edit_path(@event, party)
            - party.guests.each do |guest|
              %tr.guest{data: {guest_id: guest.id}, class: column_class}
                - if guest.full_name
                  %td.name= guest.full_name
                - else
                  %td.name.unknown= t(:unknown_guest_full_name)
                %td.status{data: {status: guest.status_for(@event),event_id: @event.id}}
                  %span.status= t(guest.status_for(@event))
                  %span.edit
                    = link_to t(:edit_this_status), 'javascript:;'
                    .options
                      = t(:mark_as)
                      %button.confirmed= t(:confirmed)
                      %button.declined= t(:declined)
                      %button.unknown= t(:unknown)
                      
                -@event.companion_events.each do |event|
                  %td.status{data: {status: guest.status_for(event),event_id: event.id}}
                    %span.status= t(guest.status_for(event))
                    %span.edit
                      = link_to t(:edit_this_status), 'javascript:;'
                      .options
                        = t(:mark_as)
                        %button.confirmed= t(:confirmed)
                        %button.declined= t(:declined)
                        %button.unknown= t(:unknown)