config/routes.rb
Envelope::Application.routes.draw do
  
  root 'homepage#index'
  
  get 'about',   to: 'homepage#about', as: :about
  get 'privacy', to: 'homepage#privacy', as: :privacy
  get 'errors', to: 'homepage#error'
  get 'errors/:status', to: 'homepage#error'
  get 'tour/:page', to: 'homepage#tour', as: :tour
  get 'tour', to: 'homepage#tour'
  
  get 'help',    to: 'support_requests#new', as: :help
  post 'help',   to: 'support_requests#create', as: :support_request_create
  
  get  'my_events', to: 'events#index', as: :my_events
  get 'my_events/:short_name', to: 'events#show', as: :main_event
  put  'my_events/:short_name', to: 'events#update'
  patch  'my_events/:short_name', to: 'events#update'
  
  delete 'events/:id', to: 'events#destroy', as: :events_destroy
  
  get 'my_events/:short_name/guests', to: 'guests#index', as: :guests_show
  post 'my_events/:short_name/parties', to: 'parties#create', as: :party_create
  post 'my_events/:short_name/guests', to: 'parties#create', as: :guests_create
  get 'my_events/:short_name/messages', to: 'messages#index', as: :messages_show
  
  get 'my_events/:short_name/guests/new', to: 'parties#new_guest', as: :guest_new
  get 'my_events/:short_name/parties/new', to: 'parties#new', as: :party_new
  get 'my_events/:short_name/parties/:id/edit', to: 'parties#edit', as: :party_edit
  put  'my_events/:short_name/parties/:id', to: 'parties#update'
  patch  'my_events/:short_name/parties/:id', to: 'parties#update', as: :party_patch

  resources :replies, only: [:create]

  devise_for :admins, path: '', path_names: {
    sign_in:  'login',
    sign_out: 'logout',
    sign_up:  'register', as: :new_user_registration
  }
  
  get ':event', to: 'reply_sets#hello', as: :site
  post ':event/attendance', to: 'reply_sets#new'
  post ':event/confirmation', to: 'reply_sets#create'
  post ':event/messages',   to: 'messages#create', as: :message_create
  
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Kindreply
    <link rel="stylesheet" type="text/css" href="//cloud.typography.com/6241872/771164/css/fonts.css" />
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = javascript_include_tag "mixpanel"
    <meta name="viewport" content="width=device-width">
  %body{class: @long_page ? 'long_page' : nil}
    = render 'shared/flash'
    = yield

app/views/layouts/dashboard.html.haml
!!!
%html
  %head
    %title Kindreply
    <link rel="stylesheet" type="text/css" href="//cloud.typography.com/6241872/771164/css/fonts.css" />
    = stylesheet_link_tag    "dashboard", media: "all"
    = javascript_include_tag "dashboard"
    = csrf_meta_tags
    = javascript_include_tag "mixpanel"
  %body
    = render 'shared/flash'
    %header
      .container        
        %p
          = link_to( t(:my_events), my_events_path)
          - if @event
            - uri_without_scheme = site_url(@event).split('//', 2)[1]
            = precede ' > ' do
              = link_to( uri_without_scheme, site_path( @event), target: '_blank')
    
    %nav#nav
      .container
        - if @event
          - class_names = (params[:controller] == 'events') ? 'active' : ''
          = link_to main_event_path(@event), {class: class_names} do
            = t(:event)
          - class_names = %w{guests parties}.include?(params[:controller]) ? 'active' : ''
          = link_to guests_show_path(@event), {class: class_names} do
            = t(:guests)
          - if @event.unexpected_guest_messages.any?
            - class_names = (params[:controller] == 'messages') ? 'active' : ''
            = link_to messages_show_path(@event), {class: class_names} do
              = t(:messages)
    = yield
    = render 'shared/footer'

app/views/layouts/errors.html.haml
!!!
%html
  %head
    %title Kindreply
    <link rel="stylesheet" type="text/css" href="//cloud.typography.com/6241872/771164/css/fonts.css" />
    %style
      = Rails.application.assets.find_asset('application.css').to_s.html_safe
    %script
      = Rails.application.assets.find_asset('application.js').to_s.html_safe
    = javascript_include_tag "mixpanel"
  %body{class: @long_page ? 'long_page' : nil}
    = yield